#!/usr/bin/python2.7
import re
import sys

stack = 0
contents = open(sys.argv[1]).readlines()

for line in contents:
    for match in re.findall(r'\(|'"'"'\)'"'"'', line):
        stack += 1
    for match in re.findall(r'\)', line):
        stack -= 1
    if stack == 0 and (len(line) > 1) and line[-2] == ',':
        line = line[:-2] + '\n'
    print line
